### ISSUE TITLE
Panics when importing URLs with no file extension

### ISSUE THREAD

**Issue by jordanreger** [sableland/sable#11]
Importing a URL with no file extension (e.g. https://esm.sh/whatwg-fetch) results in the following error:
```
thread 'main' panicked at 'Failed extracting file extension: ()', bueno/loader.rs:46:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

This is due to `bueno/loader.rs` checking for the file extension on both file imports *and* HTTP imports. This can be resolved by checking for a protocol in front of the import path (e.g. `http`, `https`, `file://`, or `()`; no protocol so default to `file://`, etc). This will allow us to check whether or not there's a `Content-Type`, which would allow for extensionless imports and therefore allow imports without explicit file extensions.

**Comment by Im-Beast** [comment]
Fixed, thanks 👍🏻
