### ISSUE TITLE
Filesystem APIs Ticket

### ISSUE THREAD

**Issue by lino-levan** [sableland/sable#4]
One of the core sets of APIs that must be available for Bueno to be useable are the file system APIs. This issue tracks all of the filesystem APIs we're missing.

- [ ] `readFile` - async read file and return uint8array
- [ ] `readFileSync` - sync version of above
- [ ] `readTextFile` - async read text file and return uint8array
- [ ] `readTextFileSync` - sync version of above
- [ ] `writeFile` - async write file form uint8array
- [ ] `writeFileSync` - sync version of above
- [ ] `writeTextFile` - async write text file form uint8array
- [ ] `writeTextFileSync` - sync version of above

We'll edit this list as we complete some. We need to discuss our file API. How should we design it? What will our `Bueno.fs.File` class (?) look like?

**Comment by Im-Beast** [comment]
Closed because of #6, it's better to keep an eye for all api's in one issue
